
_target_: src.datamodule.pubtabnet.PubTabNet
root_dir: ../../dataset/mini_pubtabnet
label_type: ${dataset.label_type}
split: train
json_html: mini_pubtabnet_examples.jsonl
transform: ${dataset.augmentation}
cell_limit: 150