[project]
name = "layout-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "layoutparser>=0.3.4",
    "setuptools>=75.5.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
