_target_: src.datamodule.PubTabNet
root_dir: ../../../../DATASETS/pubtabnet
label_type: ${dataset.label_type}
split: train
json_html: clean_html_PubTabNet_2.0.0.jsonl
transform: ${dataset.augmentation}
cell_limit: ${dataset.cell_limit}