defaults:
  - _self_
  - train/lr_scheduler: exponential
  - train/optimizer: adam

mode: train
img_size: [256,256]
label_type: image
max_seq_len: null

train:
  epochs: 20
  grad_clip: 0.2
  starting_temp: 1.
  temp_min: 0.06
  temp_anneal_rate: 1e-6
  save_every: 3
  dataloader:
    _target_: src.datamodule.dataloader.dataloader_vae
    batch_size: 48
valid:
  dataloader:
    _target_: src.datamodule.dataloader.dataloader_vae
    batch_size: 48
test:
  metrics: null


trainer:
  _target_: src.trainer.VqvaeTrainer
  snapshot: null
  model_weights: null

