_target_: src.model.components.Encoder
d_model: ${model.d_model}
nhead: ${model.nhead}
dropout: ${model.dropout}
activation: ${model.activation}
norm_first: ${model.norm_first}
nlayer: 2
ff_ratio: ${model.ff_ratio}