[project]
name = "models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "paddle2onnx>=1.2.9",
    "requests>=2.32.3",
]
