_target_: src.datamodule.augmentation.AugmentationForMIM
mean: [0.86597056, 0.88463002, 0.87491087]
std: [0.20686628, 0.18201602, 0.18485524]
trans_size: ${trainer.trans_size}
vqvae_size: ${trainer.vqvae_size}
trans_interpolation: bicubic
vqvae_interpolation: lanczos